# Generated by Django 2.2.1 on 2019-05-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharamshala', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shala',
            old_name='name',
            new_name='name_with_space',
        ),
        migrations.AddField(
            model_name='shala',
            name='name_without_space',
            field=models.CharField(default='abc', max_length=30, unique=True),
        ),
    ]
