# Generated by Django 2.2.1 on 2019-05-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharamshala', '0004_booking_booked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='blog',
            field=models.TextField(default='default blog', max_length=5000),
        ),
    ]
