# Generated by Django 2.2.1 on 2019-05-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharamshala', '0005_auto_20190522_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='from_date',
            new_name='checkin_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='to_date',
            new_name='checkout_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
    ]
