# Generated by Django 2.2.1 on 2019-05-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharamshala', '0006_auto_20190529_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(blank=True, default='select', max_length=100, null=True),
        ),
    ]
