# Generated by Django 2.2.1 on 2019-06-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharamshala', '0007_auto_20190529_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.TextField(max_length=5000)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
