# Generated by Django 2.2.2 on 2019-06-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharamshala', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shala',
            name='name_without_space',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='shala',
            name='rooms_starting_at',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='blog',
            field=models.TextField(max_length=5000),
        ),
    ]
