# Generated by Django 2.2.2 on 2019-06-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharamshala', '0011_auto_20190625_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yatri_name', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_dharamshala_or_bunglow_or_sanatorium', models.CharField(max_length=100)),
                ('name_of_dharamshala_or_bunglow_or_sanatoriumm', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_of_dharamshala_or_bunglow_or_sanatorium', models.CharField(blank=True, max_length=12, null=True)),
                ('yatri_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('yatri_phone', models.CharField(max_length=12)),
                ('no_of_yatris', models.CharField(blank=True, max_length=4, null=True)),
                ('no_and_type_of_room', models.CharField(blank=True, max_length=100, null=True)),
                ('checkin_date', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_date', models.CharField(blank=True, max_length=100, null=True)),
                ('total_days_of_stay', models.CharField(blank=True, max_length=3, null=True)),
                ('amount_received', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ref_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
