# Generated by Django 2.2.2 on 2019-06-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharamshala', '0012_voucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='name_of_dharamshala_or_bunglow_or_sanatoriumm',
            new_name='name_of_dharamshala_or_bunglow_or_sanatorium',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='date',
            new_name='today_date',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='no_of_yatris',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
