# Generated by Django 2.2.2 on 2019-07-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharamshala', '0017_shala_address_for_google_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='yatri_address',
            field=models.CharField(blank=True, default='-', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='phone_of_dharamshala_or_bunglow_or_sanatorium',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='yatri_phone',
            field=models.CharField(max_length=35),
        ),
    ]
