# Generated by Django 2.2.2 on 2019-08-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dharamshala', '0018_auto_20190712_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(blank=True, default='select', max_length=400, null=True),
        ),
    ]
